add blog
nocalhost/nocalhost.github.io pull request #208
Opened 2022-06-02 03:56 UTC by zzzhangqi

2022-06-02 04:04 UTC, zzzhangqi commented
@lxm

2022-06-02 10:16 UTC, lxm commented
Why does this PR only change a large number of contents in file `package.json`?
Maybe a markdown file should be added?

2022-06-02 10:20 UTC, zzzhangqi commented
sorry,I submitted the wrong file.Modified

2022-06-02 10:27 UTC, lxm commented on blog/rainbond-dev.md
> +- 提供易于使用的 IDE 插件（支持 VS Code 和 JetBrains），即使在 Kubernetes 集群中进行开发和调试，Nocalhost 也能保持和本地开发一样的开发体验
Nocalhost 也能保持和本地开发一样的开发体验
->  使用 Nocalhost 后也能获得和本地开发一样的开发体验

2022-06-02 10:27 UTC, lxm commented on blog/rainbond-dev.md
> +* 使用简单，不需要懂容器、Kubernetes和底层复杂技术，支持管理多个Kubernetes集群，和管理企业应用全生命周期。主要功能包括应用开发环境、应用市场、微服务架构、应用交付、应用运维、应用级多云管理等。
应用级多云管理 是否可以给一个说明？

2022-06-02 10:28 UTC, lxm commented on blog/rainbond-dev.md
> +以前我们在本地 + Rainbond 开发微服务时，要开发的模块我们运行在本地，其他模块运行在 Rainbond 上，我们通过 Rainbond 的网关与本地进行通信、联调。
在以往的开发模式中，我们在本地 + Rainbond xxxxx

2022-06-02 10:29 UTC, lxm commented on blog/rainbond-dev.md
> +
这种场景下，我们有以下问题急需解决

2022-06-02 10:41 UTC, lxm commented on blog/rainbond-dev.md
> +
这里换行的意义？

2022-06-02 10:42 UTC, lxm commented on blog/rainbond-dev.md
> +
同上

2022-06-02 10:42 UTC, lxm commented on blog/rainbond-dev.md
> +Nocalhost 支持 `VScode` `JetBrains `，这里我们主要介绍 [VScode 插件安装](https://nocalhost.dev/docs/installation "VScode 插件安装")参考官网文档。
VSCode

2022-06-02 10:42 UTC, lxm commented on blog/rainbond-dev.md
> +Nocalhost 支持 `VScode` `JetBrains `，这里我们主要介绍 [VScode 插件安装](https://nocalhost.dev/docs/installation "VScode 插件安装")参考官网文档。
Nocalhost IDE插件支持xxx

2022-06-02 10:42 UTC, lxm commented on blog/rainbond-dev.md
> +1. 打开 VScode，点击左侧的 `Extension` 按钮 ![img](https://nocalhost.dev/zh-CN/img/icons/vs-code-icon.jpg) 图标
VSCode

2022-06-02 10:43 UTC, lxm commented on blog/rainbond-dev.md
> +### 4.4 在 Rainbond 上部署 Spring Cloud 微服务
部署一个Sprint Cloud应用？

2022-06-02 10:44 UTC, lxm commented on blog/rainbond-dev.md
> +上面我们已经在本地 Vscode 中对接好了集群，并且也已经在 Rainbond 中安装了 Spring Cloud Pig 微服务，那么接下来我们在本地 Vscode 中选择其中一个组件进行开发，这里为了效果更明显，选择开发 `pig-ui` 组件。
VSCode

2022-06-02 10:45 UTC, lxm commented on blog/rainbond-dev.md
> +1. 提示选择容器，我们选择 `gred5f1c` 这个容器，剩下那个容器是 Rainbond 的 Mesh 容器，用于内部通信，不可替换
”剩下那个容器“ 是哪个容日，应该给出来一个具体的描述，便于用户理解

2022-06-02 10:46 UTC, lxm commented on blog/rainbond-dev.md
> +3. 等待片刻后，会默认打开远端容器的终端界面并且容器内的文件会与本地实时同步，如下：
默认应该是将本地项目的文件同步至容器，“容器内的文件会与本地实时同步” 这个容易有歧义

2022-06-02 10:48 UTC, lxm requested changes

2022-06-02 10:48 UTC, lxm commented on blog/rainbond-dev.md
> +	 ```shell
这里空格的原因？

2022-06-02 10:48 UTC, lxm commented on blog/rainbond-dev.md
> +    ```shell
缩进

2022-06-02 10:48 UTC, lxm commented on blog/rainbond-dev.md
> +通过以上的实践步骤，我们已经可以通过 Nocalhost 开发 Rainbond 上的微服务应用，摆脱本地开发，进入云原生快速开发，提升我们的开发效率。
摆脱本地开发这个描述不准确

2022-06-02 10:56 UTC, zzzhangqi commented on blog/rainbond-dev.md
> +现在我们通过 Nocalhost + Rainbond 开发微服务时，所有服务都运行在 Rainbond 上，当要开发时本地 Vscode 直连到 Rainbond 组件中，并与本地代码实时同步到 Rainbond 组件中。多人开发联调时，可通过 Rainbond 内置的 Service Mesh 进行服务之间联调。
"当要开发时本地 Vscode 直连到 Rainbond 组件中"  这句修改为：

在开发过程中可以使用 VSCode 插件 Nocalhost 连接进入到 Rainbond 组件中

2022-06-02 10:57 UTC, zzzhangqi commented on blog/rainbond-dev.md
> +
工具引起的换行，已修复

2022-06-02 10:58 UTC, zzzhangqi commented on blog/rainbond-dev.md
> +### 4.4 在 Rainbond 上部署 Spring Cloud 微服务
修改为  在 Rainbond 上部署 Spring Cloud 应用

2022-06-02 11:03 UTC, zzzhangqi commented on blog/rainbond-dev.md
> +3. 等待片刻后，会默认打开远端容器的终端界面并且容器内的文件会与本地实时同步，如下：
修改为：等待片刻后，会默认打开远端容器的终端界面并且将本地项目的文件同步至容器内

2022-06-02 11:04 UTC, zzzhangqi commented on blog/rainbond-dev.md
> +通过以上的实践步骤，我们已经可以通过 Nocalhost 开发 Rainbond 上的微服务应用，摆脱本地开发，进入云原生快速开发，提升我们的开发效率。
“摆脱本地开发” 
删除这句话，避免歧义

2022-06-02 11:10 UTC, zzzhangqi commented on blog/rainbond-dev.md
> +* 使用简单，不需要懂容器、Kubernetes和底层复杂技术，支持管理多个Kubernetes集群，和管理企业应用全生命周期。主要功能包括应用开发环境、应用市场、微服务架构、应用交付、应用运维、应用级多云管理等。
这里不过多介绍产品了

2022-06-02 11:17 UTC, lxm commented
lgtm

2022-06-07 03:15 UTC, yuanganping commented on blog/rainbond-dev.md
> +*  Repliace DevMode
Replace DevMode

2022-06-07 03:27 UTC, zzzhangqi commented on blog/rainbond-dev.md
> +*  Repliace DevMode
Handled

2022-06-07 08:07 UTC, merged